theme: jekyll-theme-chirpy
lang: ko
timezone: Asia/Seoul

title: Whitehander's Log
tagline:
description: >-
  "Whitehander's Tech & Life Blog"
url: "https://whitehander.github.io"
github:
  username: whitehander
social:
  name: Sangmin Jung
  email: ggami7282@gmail.com
  links:
    - https://github.com/whitehander
    - https://www.linkedin.com/in/whitehander
theme_mode:
img_cdn: "https://whitehander.github.io"
avatar: /assets/whmark.jpg
toc: true

pwa:
  enabled: true

paginate: 5
paginate_path: /page/:num

baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /:categories/:year/:month/:day/:title.html
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
